version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - db_data:/docker-entrypoint-initdb.d
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  php:
    image: php:8.2-apache
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - appnet
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    build:
      context: ./docker
    container_name: nginx_proxy
    ports:
      - "4500:4500"
    depends_on:
      - php
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db_data:

networks:
  appnet:
    driver: overlay
